### ISSUE TITLE
🐛 ModuleNotFoundError: No module named 'maro.cli'; 'maro' is not a package

### ISSUE THREAD

**Issue by clm971910** [microsoft/maro#213]
(maro_venv) ali-6c96cfd90593:maro yewang$ python cli/maro.py 
Traceback (most recent call last):
  File "cli/maro.py", line 10, in <module>
    import maro.cli.utils.examples as CliExamples
  File "/Users/yewang/Documents/maro/maro/cli/maro.py", line 10, in <module>
    import maro.cli.utils.examples as CliExamples
ModuleNotFoundError: No module named 'maro.cli'; 'maro' is not a package

**Comment by romic7x** [comment]
Hi, sorry for the late response. Please use the command 'maro' directly, if you install it correctly, we do not have to use python to activate the CLI.
Ref: https://maro.readthedocs.io/en/latest/installation/grass_cluster_provisioning_on_azure.html

**Comment by romic7x** [comment]
And btw, we are still refining the CLI, pls be patient and we will release more features in v0.2

**Comment by ArthurJiang** [comment]
@romic7x has provided an answer.

**Comment by yangboz** [comment]
> (maro_venv) ali-6c96cfd90593:maro yewang$ python cli/maro.py Traceback (most recent call last): File "cli/maro.py", line 10, in import maro.cli.utils.examples as CliExamples File "/Users/yewang/Documents/maro/maro/cli/maro.py", line 10, in import maro.cli.utils.examples as CliExamples ModuleNotFoundError: No module named 'maro.cli'; 'maro' is not a package

And
Traceback (most recent call last):
  File "/Users/apple/miniconda3/envs/msmaropy37/bin/maro", line 8, in <module>
    sys.exit(main())
  File "/Users/apple/miniconda3/envs/msmaropy37/lib/python3.7/site-packages/maro/cli/maro.py", line 100, in main
    load_parser_inspector(parser_inspector, global_parser)
  File "/Users/apple/miniconda3/envs/msmaropy37/lib/python3.7/site-packages/maro/cli/maro.py", line 1015, in load_parser_inspector
    from maro.cli.maro_real_time_vis.start_maro_geo_vis import start_geo_vis
  File "/Users/apple/miniconda3/envs/msmaropy37/lib/python3.7/site-packages/maro/cli/maro_real_time_vis/start_maro_geo_vis.py", line 13, in <module>
    from .back_end.vis_app.data_process.request.request_params import request_settings
ModuleNotFoundError: No module named 'maro.cli.maro_real_time_vis.back_end.vis_app.data_process'
