### ISSUE TITLE
📚 Can not realize the example as Readme

### ISSUE THREAD

**Issue by Ivens-Zhang** [microsoft/maro#248]
## Description

Firstly, I run a container by `arthursjiang/maro:cpu`, and copy the example in readme(`Quick Example`) with part of  `Environment Visualization` and run it:

```python
from maro.simulator import Env

# Enable environment dump feature, when initializing the environment instance
env = Env(scenario="cim",
          topology="toy.5p_ssddd_l0.0",
          start_tick=0,
          durations=100,
          options={"enable-dump-snapshot": "./dump_data"})

metrics, decision_event, is_done = env.step(None)

while not is_done:
    metrics, decision_event, is_done = env.step(None)

print(f"environment metrics: {env.metrics}")
```

but it will show me this error log:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-2bba340a34d8> in <module>
      1 from maro.simulator import Env
      2 
----> 3 env = Env(scenario="cim", topology="toy.5p_ssddd_l0.0", start_tick=0, durations=100, options={"enable-dump-snapshot": "./dump_data"})
      4 
      5 metrics, decision_event, is_done = env.step(None)

/usr/local/lib/python3.6/site-packages/maro/simulator/core.py in __init__(self, scenario, topology, start_tick, durations, snapshot_resolution, max_snapshots, decision_mode, business_engine_cls, disable_finished_events, options)
     69             parent_path = self._additional_options["enable-dump-snapshot"]
     70             self._converter = DumpConverter(parent_path, self._business_engine._scenario_name)
---> 71             self._converter.reset_folder_path()
     72 
     73     def step(self, action):

/usr/local/lib/python3.6/site-packages/maro/data_lib/dump_csv_converter.py in reset_folder_path(self)
     51 
     52     def reset_folder_path(self):
---> 53         self._generate_new_folder(self._parent_path)
     54         self._serial = 0
     55 

/usr/local/lib/python3.6/site-packages/maro/data_lib/dump_csv_converter.py in _generate_new_folder(self, parent_path)
     36         if folder_path.exists():
     37             return
---> 38         os.mkdir(self._foldername)
     39 
     40     @property

FileNotFoundError: [Errno 2] No such file or directory: './dump_data/snapshot_dump_2021_01_11_03_01_56_834'
```

I realized this will caused by this file (`dump_data`) does not in this folder. So, I use FIND script try to find out where the file is. But, the log like this:

```bash
shaiic@zy-openpai-marketplace:~/zhangy/maro$ ls
CHANGELOG.md  CITATION  CODE_OF_CONDUCT.md  CONTRIBUTING.md  LICENSE  MANIFEST.in  README.md  SECURITY.md  docker_files  docs  examples  maro  notebooks  playground.md  pyproject.toml  requirements.dev.txt  scripts  setup.py  tests
shaiic@zy-openpai-marketplace:~/zhangy/maro$ find . -name "dump_data.*"
shaiic@zy-openpai-marketplace:~/zhangy/maro$ find . -name "dump_data"
```

This is my server configuration:

```bash
shaiic@zy-openpai-marketplace:~/zhangy/maro$ neofetch 
            .-/+oossssoo+/-.               shaiic@zy-openpai-marketplace 
        `:+ssssssssssssssssss+:`           ----------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.5 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: Virtual Machine 7.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-1031-azure 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 68 days, 1 hour, 39 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 640 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.20 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: vscode 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon Platinum 8171M (4) @ 2.095GHz 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: Microsoft Corporation Hyper-V virtual VGA 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 753MiB / 15987MiB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss. 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                            
  +sssssssssdmydMMMMMMMMddddyssssssss+ 
   /ssssssssssshdmNNNNmyNMMMMhssssss/ 
    .ossssssssssssssssssdMMMNysssso. 
      -+sssssssssssssssssyyyssss+- 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-. 
```

So, How can I get result like this?

![](https://github.com/microsoft/maro/raw/master/docs/source/images/visualization/dashboard/cim_inter_epoch.gif)

By the way, should I install Maro by resouce code before Or What dependence I need to get before to run script in Readme.md L149?

```
# Inspect environment with the dump data
maro inspector env --source ./dump_data
```

**Comment by micli** [comment]
Hi Ivens:

You should create dump_data folder by yourself before you running code.  I think there two reasons that use should create folder than automatic create:
1. The dump folder might be in a complex path that parent/grand parent level does not exist. Env class might not have enough permissions to create folders in each level.
2. User should guarantee the dump folder has permissions and enough spaces for dumping data.

Please create dump_data folder by yourself. 
Thanks!

**Comment by Allen-labs** [comment]
@ArthurJiang @Ivens-Zhang  I have an error running the single_process_launcher.py file in the maro/examples/cim/ dqn directory
```
[root@vm01 dqn]# python3 single_process_launcher.py 
Traceback (most recent call last):
  File "single_process_launcher.py", line 56, in <module>
    launch(config)
  File "single_process_launcher.py", line 49, in launch
    learner.learn()
  File "/usr/local/lib64/python3.6/site-packages/maro/rl/learner/simple_learner.py", line 45, in learn
    exploration_params=exploration_params
  File "/usr/local/lib64/python3.6/site-packages/maro/rl/actor/simple_actor.py", line 39, in roll_out
    self._env.reset()
  File "/usr/local/lib64/python3.6/site-packages/maro/simulator/core.py", line 111, in reset
    self._converter.start_processing(self._business_engine.name_mapping_file_path)
AttributeError: 'CimBusinessEngine' object has no attribute 'name_mapping_file_path'
```
After modifying line 111 in the maro/simulator/core.py file, I successfully run single_process_launcher.py
`self._business_engine.name_mapping_file_path  --> Self. _business_engine. _config_path`

**Comment by Allen-labs** [comment]
@ArthurJiang @Ivens-Zhang  I also had an error when executing the maro Inspector:
```
[root@vm01 dqn]# maro inspector env --source_path snapshot_dump_2021_01_19_03_06_14_734/
Generating Dashboard Data.
Traceback (most recent call last):
  File "/usr/local/bin/maro", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.6/site-packages/maro/cli/maro.py", line 125, in main
    args.func(**actual_args)
  File "/usr/local/lib64/python3.6/site-packages/maro/cli/inspector/env_data_process.py", line 63, in start_vis
    _get_index_index_name_conversion(scenario, source_path, conversion_path)
  File "/usr/local/lib64/python3.6/site-packages/maro/cli/inspector/env_data_process.py", line 225, in _get_index_index_name_conversion
    conversion = cim_information["ports"].keys()
TypeError: string indices must be integers
```
After modifying the maro/cli/inspector/env_data_process.py file, I ran it successfully，I think there was an error loading the configuration file，cim_information should be a dict , not a str

**Comment by chaosddp** [comment]
I think it should business_engine.configs, not the path, need @micli to confirm.

**Comment by Allen-labs** [comment]
@chaosddp Thanks a lot. I agree with you.

**Comment by micli** [comment]
> @chaosddp Thanks a lot. I agree with you.

Hi Allen:
I've submitted a PR waiting for approve. That will fix this bug. You need to run below commands:
> go to root folder of maro
> bash scripts/install_maro.sh(Linux/macOS) or scripts/install_maro.bat
When build completed, it will work correctly.

**Comment by Allen-labs** [comment]
@micli Thank you, I'll try it

**Comment by chaosddp** [comment]
Close it as it was fixed, feel free to re-open it if there is any problem.
