### ISSUE TITLE
Regression? examples/rl/workflows/simple_learner.py  cannot run anymore🐛 

### ISSUE THREAD

**Issue by susanhuhu** [microsoft/maro#403]
susan@vm-2:~/maro$ python ./examples/rl/workflows/simple_learner.py 
Traceback (most recent call last):
  File "./examples/rl/workflows/simple_learner.py", line 14, in <module>
    from agent_wrapper import get_agent_wrapper
  File "/home/susan/maro/examples/rl/workflows/agent_wrapper.py", line 13, in <module>
    from general import agent2policy, non_rl_policy_func_index, rl_policy_func_index
  File "/home/susan/maro/examples/rl/workflows/general.py", line 21, in <module>
    module = importlib.import_module(f"{config['scenario']}")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/susan/maro/examples/rl/supply_chain/__init__.py", line 4, in <module>
    from .env_wrapper import get_env_wrapper
  File "/home/susan/maro/examples/rl/supply_chain/env_wrapper.py", line 1173, in <module>
    tmp_env_wrapper = get_env_wrapper(replay_agent_ids=[])
  File "/home/susan/maro/examples/rl/supply_chain/env_wrapper.py", line 1170, in get_env_wrapper
    return SCEnvWrapper(env=Env(**env_config), replay_agent_ids=replay_agent_ids)
  File "/home/susan/maro/examples/rl/supply_chain/env_wrapper.py", line 85, in __init__
    super().__init__(env, reward_eval_delay, replay_agent_ids=replay_agent_ids)
  File "/home/susan/maro/maro/rl/learning/env_wrapper.py", line 69, in __init__
    self._replay_buffer = {agent_id: defaultdict(list) for agent_id in replay_agent_ids}
  File "/home/susan/maro/maro/rl/learning/env_wrapper.py", line 69, in <dictcomp>
    self._replay_buffer = {agent_id: defaultdict(list) for agent_id in replay_agent_ids}
TypeError: unhashable type: 'SkuInfo'

**Comment by ysqyang** [comment]
This issue has been fixed on an internal testing branch that has not been published to the repo yet. I will update this branch with the latest RL toolkit and the AKS scripts and publish it in the next few days. Thanks for your patience.
