### ISSUE TITLE
Issue on page /scenarios/command_line.html

### ISSUE THREAD

**Issue by yangboz** [microsoft/maro#448]
(msmaro) apple@appledeMacBook-Pro msmaro % maro project new
Traceback (most recent call last):
  File "/Users/apple/miniconda3/envs/msmaro/bin/maro", line 5, in <module>
    from maro.cli.maro import main
  File "/Users/apple/miniconda3/envs/msmaro/lib/python3.6/site-packages/maro/cli/maro.py", line 11, in <module>
    from maro import __version__
ImportError: cannot import name '__version__'

**Comment by yangboz** [comment]
used conda  to  create a clean py38  env, then install pymaro from source, fixed it.
